# Generated by Django 5.2.8 on 2025-11-26 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyntrade', '0002_category_listing_comment_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
