# Generated by Django 6.0.3 on 2026-07-11 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_community_posts(apps, schema_editor):
    CommunityPost = apps.get_model("buyntrade", "CommunityPost")
    if CommunityPost.objects.exists():
        return

    CommunityPost.objects.bulk_create([
        CommunityPost(
            author_name="Thabo M.",
            role="Verified Trader",
            text="Just traded my old laptop for a gaming monitor. BuyNTrade made the whole process smooth and safe.",
            likes=1103,
            is_featured=True,
        ),
        CommunityPost(
            author_name="Lerato K.",
            role="Top Seller",
            text="Love how easy it is to list items and connect with buyers in my area. Highly recommend!",
            likes=105,
            is_featured=True,
        ),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('buyntrade', '0005_alter_bid_id_alter_category_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=64)),
                ('role', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('likes', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(seed_community_posts, migrations.RunPython.noop),
    ]
